### ISSUE TITLE
Install the NBX Tool 

### ISSUE THREAD

**Issue by grichardomi** [nanobox-io/nbx#4]
curl -sSL get.nanobox.io | sudo sh, gets me the following:

sh: 6: [[: not found
sh: 8: [[: not found
Downloading nbx...
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information

I'm on Ubuntu. What did  I do wrong?

**Comment by tylerflint** [comment]
Can you try this and see if you get better results: `curl -sSL get.nanobox.io | sudo bash`

Thanks!

**Comment by grichardomi** [comment]
Tyler, it worked. Thank you!
